# Generated by Django 6.0.1 on 2026-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0012_videolecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationdata',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
