# Generated by Django 6.0.1 on 2026-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0013_userregistrationdata_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolecture',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to YouTube, Vimeo, or other video platforms', null=True),
        ),
    ]
