# Generated by Django 6.0.1 on 2026-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0014_remove_videolecture_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='video_url',
            field=models.URLField(default='https://example.com/placeholder-video', help_text='Link to YouTube, Vimeo, or other video platforms'),
            preserve_default=False,
        ),
    ]
