# Generated by Django 6.0.1 on 2026-05-09 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0015_alter_videolecture_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, help_text='For video resources only: Link to YouTube, Vimeo, or other video platforms', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'mp4', 'webm', 'ogg'])]),
        ),
    ]
