# Generated by Django 6.0.1 on 2026-05-09 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0016_resource_video_url_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_lectures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to YouTube, Vimeo, or other video platforms', null=True),
        ),
    ]
