# Generated by Django 6.0.1 on 2026-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0017_videolecture_video_file_alter_videolecture_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolecture',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=placeholder', help_text='Link to YouTube, Vimeo, or other video platforms (Required)'),
        ),
    ]
